version: "3.8"

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    # ملاحظة: container_name يتم تجاهله في Swarm، الـ Stack يعطيه اسماً تلقائياً
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD:-YourStrongPassword123!}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql/data
    networks:
      - ecom_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${MSSQL_PASSWORD:-YourStrongPassword123!} -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure

  backend:
    image: ghcr.io/developerziad/ecom-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=db;Database=EcomStoreDB;User Id=sa;Password=${MSSQL_PASSWORD:-YourStrongPassword123!};TrustServerCertificate=True
    ports:
      - "5000:8080"
    # [التصحيح]: في Swarm الـ depends_on يجب أن تكون قائمة أسماء فقط
    depends_on:
      - db
    networks:
      - ecom_network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  frontend:
    image: ghcr.io/developerziad/ecom-frontend:latest
    build:
      context: ./EcomFront
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - ecom_network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  ecom_network:
    driver: overlay
    attachable: true # يسمح للحاويات العادية بالاتصال بالشبكة إذا لزم الأمر

volumes:
  sql_data:
